version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jacoco-maven-plugin"
        versions: ["0.8.x"]
      - dependency-name: "org.osgi.service.component.annotations"
        versions: ["1.x"]
      - dependency-name: "org.osgi.service.log"
        versions: ["1.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
