name: Build & Verify

on:
  pull_request:
    branches:
      - main

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        profile: [aemCloudService, java8, aem65, java8aem65]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: maven

      - name: Build & Test with Maven
        run: mvn -U clean verify -P${{ matrix.profile }}

      - name: Upload CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: core/target/site/jacoco/jacoco.xml
          flags: unittests
