name: Build & Verify

on:
  pull_request:
    branches:
      - main

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - aemVersion: "CloudService"
          - aemVersion: "65"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11
          cache: maven

      - name: Build & Test with Maven
        run: mvn -U clean verify -Paem{{ matrix.aemVersion }}

      - name: Upload CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: core/target/site/jacoco/jacoco.xml
          flags: unittests
