name: Build & Verify

on:
  pull_request:
    branches:
      - main

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        aem: [aemCloudService, aem65]
        jdk: [8, 11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: maven

      - name: Build & Test with Maven
        run: mvn -U clean verify -P${{ matrix.aem }}

      - name: Upload CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: core/target/site/jacoco/jacoco.xml
          flags: unittests
