name: Build & Verify

on:
  pull_request:
    branches:
      - main

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        profile:
          - 'aemaacsDeps,aemaacs'
          - 'aem65deps,aem65'
          - 'aem65deps,java8aem65'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: maven

      - name: Build & Test with Maven
        run: mvn -U clean verify -P${{ matrix.profile }}

      - name: Upload CodeCov
        uses: codecov/codecov-action@v4.5.0
        with:
          file: core/target/site/jacoco/jacoco.xml
          flags: unittests
