name: Build & Verify

on:
  pull_request:
    branches:
      - main

jobs:
  maven-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11
          cache: maven

      - name: Build & Test with Maven
        run: mvn -U clean verify

      - name: Upload CodeCov
        uses: codecov/codecov-action@v2.0.3
        with:
          file: core/target/site/jacoco/jacoco.xml
          flags: unittests
